services:
  postgres:
    image: postgres:16
    container_name: depostgres
    restart: always
    environment:
      POSTGRES_USER: deuser
      POSTGRES_PASSWORD: depassword
      POSTGRES_DB: de_practice
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: